import jsPDF from "jspdf";
import type { FullProfile } from "@/lib/types/profile";
import { format } from "date-fns";

/**
 * Generates a professional CV/Resume PDF from profile data
 * Features CPS Intern branding and HR-ready layout
 */
export async function generateProfileCV(profile: FullProfile): Promise<void> {
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    // Colors
    const primaryColor: [number, number, number] = [99, 102, 241]; // Indigo
    const textColor: [number, number, number] = [31, 41, 55];
    const mutedColor: [number, number, number] = [107, 114, 128];

    // Helper functions
    const addSection = (title: string) => {
        y += 8;
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...primaryColor);
        doc.text(title.toUpperCase(), margin, y);
        y += 2;
        doc.setDrawColor(...primaryColor);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;
        doc.setTextColor(...textColor);
        doc.setFont("helvetica", "normal");
    };

    const addParagraph = (text: string, fontSize = 10) => {
        doc.setFontSize(fontSize);
        const lines = doc.splitTextToSize(text, contentWidth);
        doc.text(lines, margin, y);
        y += lines.length * (fontSize * 0.4) + 4;
    };

    const checkPageBreak = (neededSpace: number) => {
        if (y + neededSpace > pageHeight - margin) {
            doc.addPage();
            y = margin;
        }
    };

    // =============================================
    // HEADER / BRANDING
    // =============================================
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 45, "F");

    // Name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(profile.full_name || "Professional CV", margin, 20);

    // Headline
    if (profile.headline) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text(profile.headline, margin, 28);
    }

    // Contact info row
    doc.setFontSize(9);
    const contactParts: string[] = [];
    if (profile.email) contactParts.push(profile.email);
    if (profile.phone) contactParts.push(profile.phone);
    if (profile.location) contactParts.push(profile.location);
    if (profile.website) contactParts.push(profile.website);

    if (contactParts.length > 0) {
        doc.text(contactParts.join("  |  "), margin, 38);
    }

    // CPS Intern branding
    doc.setFontSize(8);
    doc.text("Generated by CPS Intern", pageWidth - margin - 35, 38);

    y = 55;

    // =============================================
    // ABOUT / SUMMARY
    // =============================================
    if (profile.about) {
        addSection("Professional Summary");
        addParagraph(profile.about);
    }

    // =============================================
    // SKILLS
    // =============================================
    if (profile.skills.length > 0) {
        checkPageBreak(30);
        addSection("Skills");
        const skillNames = profile.skills.map((s) => s.skill_name).join("  •  ");
        doc.setFontSize(10);
        const skillLines = doc.splitTextToSize(skillNames, contentWidth);
        doc.text(skillLines, margin, y);
        y += skillLines.length * 4 + 6;
    }

    // =============================================
    // EXPERIENCE
    // =============================================
    if (profile.experiences.length > 0) {
        checkPageBreak(40);
        addSection("Experience");

        for (const exp of profile.experiences) {
            checkPageBreak(25);

            // Title and company
            doc.setFontSize(11);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...textColor);
            doc.text(exp.title, margin, y);
            y += 4;

            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.text(exp.company, margin, y);

            // Date range (right aligned)
            const dateRange = `${exp.start_date ? format(new Date(exp.start_date), "MMM yyyy") : ""} - ${exp.current ? "Present" : exp.end_date ? format(new Date(exp.end_date), "MMM yyyy") : ""}`;
            doc.setFontSize(9);
            doc.setTextColor(...mutedColor);
            doc.text(dateRange, pageWidth - margin, y, { align: "right" });
            y += 5;

            // Description
            if (exp.description) {
                doc.setTextColor(...textColor);
                doc.setFontSize(9);
                const descLines = doc.splitTextToSize(exp.description, contentWidth);
                doc.text(descLines, margin, y);
                y += descLines.length * 3.5 + 4;
            } else {
                y += 4;
            }
        }
    }

    // =============================================
    // EDUCATION
    // =============================================
    if (profile.education.length > 0) {
        checkPageBreak(40);
        addSection("Education");

        for (const edu of profile.education) {
            checkPageBreak(20);

            doc.setFontSize(11);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...textColor);
            doc.text(edu.school, margin, y);
            y += 4;

            if (edu.degree || edu.field) {
                doc.setFontSize(10);
                doc.setFont("helvetica", "normal");
                const degreeLine = [edu.degree, edu.field].filter(Boolean).join(" in ");
                doc.text(degreeLine, margin, y);
            }

            // Years (right aligned)
            const years = [edu.start_year, edu.end_year].filter(Boolean).join(" - ");
            if (years) {
                doc.setFontSize(9);
                doc.setTextColor(...mutedColor);
                doc.text(years, pageWidth - margin, y, { align: "right" });
            }
            y += 6;
        }
    }

    // =============================================
    // PROJECTS
    // =============================================
    if (profile.projects.length > 0) {
        checkPageBreak(40);
        addSection("Projects");

        for (const proj of profile.projects) {
            checkPageBreak(20);

            doc.setFontSize(11);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...textColor);
            doc.text(proj.title, margin, y);
            y += 4;

            if (proj.description) {
                doc.setFontSize(9);
                doc.setFont("helvetica", "normal");
                const projLines = doc.splitTextToSize(proj.description, contentWidth);
                doc.text(projLines, margin, y);
                y += projLines.length * 3.5;
            }

            if (proj.link) {
                doc.setFontSize(8);
                doc.setTextColor(...primaryColor);
                doc.text(proj.link, margin, y);
                y += 3;
            }

            if (proj.tags && proj.tags.length > 0) {
                doc.setFontSize(8);
                doc.setTextColor(...mutedColor);
                doc.text(`Technologies: ${proj.tags.join(", ")}`, margin, y);
                y += 4;
            }

            y += 2;
        }
    }

    // =============================================
    // RECOMMENDATIONS
    // =============================================
    if (profile.recommendations.length > 0) {
        checkPageBreak(40);
        addSection("Recommendations");

        for (const rec of profile.recommendations.slice(0, 2)) {
            checkPageBreak(25);

            doc.setFontSize(9);
            doc.setFont("helvetica", "italic");
            doc.setTextColor(...textColor);
            const recLines = doc.splitTextToSize(`"${rec.message}"`, contentWidth);
            doc.text(recLines, margin, y);
            y += recLines.length * 3.5 + 2;

            doc.setFont("helvetica", "bold");
            doc.text(`— ${rec.author_name}`, margin, y);
            if (rec.author_title) {
                doc.setFont("helvetica", "normal");
                doc.setTextColor(...mutedColor);
                doc.text(`, ${rec.author_title}`, margin + doc.getTextWidth(`— ${rec.author_name}`), y);
            }
            y += 8;
        }
    }

    // =============================================
    // FOOTER
    // =============================================
    doc.setFontSize(8);
    doc.setTextColor(...mutedColor);
    doc.text(
        `Generated on ${format(new Date(), "MMMM d, yyyy")} via CPS Intern`,
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
    );

    // Download
    const filename = `${(profile.full_name || "profile").replace(/\s+/g, "_")}_CV.pdf`;
    doc.save(filename);
}
